NT Align commit hash with latest commit on failure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,13 +28,6 @@ jobs:
           unzip -j saxon.zip 'saxon.jar' -d utilities/saxon655
           rm saxon.zip
        
-      - name: Set environment variables
-        run: |
-          # Define the release version using UTC in the format CCMMYYDD-HHMMZ
-          echo "RELEASE_VERSION=$(date -u +'%C%y%m%d-%H%MZ')" >> $GITHUB_ENV
-          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
-          echo "COMMIT_HASH_SHORT=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
-                    
       - name: Set up Git
         run: |
           # ensure GitHub/Repository/Settings/Actions/General/ActionsPermissions is allow all actions
@@ -52,12 +45,69 @@ jobs:
           echo >>makedoc.log.txt
           echo Returned error: $returnerror >>makedoc.log.txt
           echo >>makedoc.log.txt
-          echo Branch:  $BRANCH_NAME >>makedoc.log.txt
-          echo Release: $RELEASE_VERSION >>makedoc.log.txt
           if [ $returnerror -ne 0 ]; then
+            # annotate message log on failure
+            echo "RELEASE_VERSION=$(date -u +'%C%y%m%d-%H%MZ')" >> $GITHUB_ENV
+            echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
+            echo "COMMIT_HASH_SHORT=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
+            echo Branch:   $BRANCH_NAME >>makedoc.log.txt
+            echo Commit:   $COMMIT_HASH_SHORT >>makedoc.log.txt
+            echo Run date: $RELEASE_VERSION >>makedoc.log.txt
             exit 1
           fi
         continue-on-error: true   # Allow the workflow to continue even if this step fails
+
+      - name: Commit changes
+        if: success()  # Only commit if the build was successful
+        run: |
+          git add .
+          if ! git diff-index --quiet HEAD --; then
+            git commit -m "Update documentation from push action"
+            NEW_COMMIT_SHA=$(git rev-parse HEAD)
+            echo "NEW_COMMIT_SHA=$NEW_COMMIT_SHA" >> $GITHUB_ENV
+            git push
+          else
+            echo "No changes to documentation to be committed"
+            NEW_COMMIT_SHA=""
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Wait for push to complete
+        if: success()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NEW_COMMIT_SHA: ${{ env.NEW_COMMIT_SHA }}
+        run: |
+          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
+          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
+          if [ -n "$NEW_COMMIT_SHA" ]; then
+            for i in {2..10}; do
+              sleep $((2**i))
+              if gh api repos/$OWNER/$REPO/commits/$NEW_COMMIT_SHA --silent; then
+                echo "Push completed"
+                break
+              else
+                echo "Push not yet completed. Retrying in $((2**i)) seconds..."
+              fi
+            done
+          else
+            echo "No new commit was created. Skipping wait for push."
+          fi
+          
+      - name: Set environment variables
+        run: |
+          # Define the release version using UTC in the format CCMMYYDD-HHMMZ
+          echo "RELEASE_VERSION=$(date -u +'%C%y%m%d-%H%MZ')" >> $GITHUB_ENV
+          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
+          echo "COMMIT_HASH_SHORT=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
+                    
+      - name: Annotate message log on success
+        if: success()  # Had there been a failure, the log already is annotated
+        run |
+            echo Branch:   $BRANCH_NAME >>makedoc.log.txt
+            echo Commit:   $COMMIT_HASH_SHORT >>makedoc.log.txt
+            echo Run date: $RELEASE_VERSION >>makedoc.log.txt
 
       - name: Upload artefacts for action - log and HTML file
         if: always()  # Always upload log file even if previous steps failed
@@ -105,44 +155,6 @@ jobs:
             download/*
             !download/crane-designSVG2burnFiles--${{ env.RELEASE_VERSION }}-${{ env.BRANCH_NAME }}-${{ env.COMMIT_HASH_SHORT }}.zip
 
-      - name: Commit changes
-        if: success()  # Only commit if the build was successful
-        run: |
-          git add .
-          if ! git diff-index --quiet HEAD --; then
-            git commit -m "Update documentation from push action"
-            NEW_COMMIT_SHA=$(git rev-parse HEAD)
-            echo "NEW_COMMIT_SHA=$NEW_COMMIT_SHA" >> $GITHUB_ENV
-            git push
-          else
-            echo "No changes to documentation to be committed"
-            NEW_COMMIT_SHA=""
-          fi
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Wait for push to complete
-        if: success()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NEW_COMMIT_SHA: ${{ env.NEW_COMMIT_SHA }}
-        run: |
-          OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
-          REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
-          if [ -n "$NEW_COMMIT_SHA" ]; then
-            for i in {2..10}; do
-              sleep $((2**i))
-              if gh api repos/$OWNER/$REPO/commits/$NEW_COMMIT_SHA --silent; then
-                echo "Push completed"
-                break
-              else
-                echo "Push not yet completed. Retrying in $((2**i)) seconds..."
-              fi
-            done
-          else
-            echo "No new commit was created. Skipping wait for push."
-          fi
-          
       - name: Install GitHub CLI
         if: ${{ success() && (github.ref == 'refs/heads/main') }}
         run: sudo apt-get install -y gh
